### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by jerneyio** [mulesoft-labs/data-weave-native#10]
**Is your feature request related to a problem? Please describe.**
Users shouldn't need to come to github, download a zip and move files around. Getting this on Homebrew would help Macintosh users. Not sure about other package manager or other platforms like Windows. This would also make pulling in updates to data-weave-native a lot less painful.

**Describe the solution you'd like**
`brew install dw`

**Describe alternatives you've considered**
The alternative might be a script in the root of the project that deals with the installation, but then it's just a lot of custom scripting that Homebrew would normally handle.

**Comment by machaval** [comment]
100% agree for windows I know there is something called `chocolate` but I don't know how to do any of this so I would need to investigate. Also having .deb and .rpm for linux or using new packaging system.

**Comment by machaval** [comment]
Brew support was done
