### ISSUE TITLE
`-path` default

### ISSUE THREAD

**Issue by jerneyio** [mulesoft-labs/data-weave-native#13]
`-path` should default to something like `~/.dw/libs` so users don't need to enter this over and over if they're using Modules. DW should also look for a variable present like `DW_LIB_PATH`. Precedence would be as follows:

1. Modules location set with `dw -path`
2. Modules location set with `DW_LIB_PATH`
3. Default module location

**Comment by machaval** [comment]
I think this is already like this just lack of documentation
