### ISSUE TITLE
Environment variables accessible

### ISSUE THREAD

**Issue by chrysophylax** [mulesoft-labs/data-weave-native#17]
**Is your feature request related to a problem? Please describe.**
I was wondering if this CLI / Native version supports accessing environment variables and the like. In the embedded Mule version, we see the ability to query the local context using the p() function.
Is this supported in the CLI for environment variables?

**Describe the solution you'd like**
I would like to be able to inject a variable map with an arbitrary name. This would be accessible using a pre-defined keyword `vars` in the script. If I need to set a variable based on say, the current hostname + kernel version of the server, I could run something like 

```
$ export chost=`(uname -sra)`
$ dw -i payload state.json -v 'host: "$chost" ' "output application/json --- payload mergeWith vars.host"
```

I am reminded of how cURL does headers for HTTP calls. Adding this style of params/vars would be very helpful in making scripts more flexible on the server-side instead of having to stringbash the resulting JSON with sed.
cURL uses -H, perhaps dw could use -V or -v
**Describe alternatives you've considered**
Not using dataweave native

**Comment by machaval** [comment]
Hi @chrysophylax there is a way to access environment variables and is by using the 

```dw::System``` 

- https://docs.mulesoft.com/mule-runtime/4.2/dw-system-functions-envvar 

`dw "dw::System::envVar('chost')"`
