### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by jmasseoavio** [mulesoft-labs/data-weave-native#18]
**Describe the bug**
Get no output on Linux to stdout or specified output file.

**To Reproduce**
Download Binary.  Extract to $HOME/.dw.  Attempt to run any of the examples from the README.

**Expected behavior**
Output.

Attempted to execute on Fedora 31 and Ubuntu 18.04.

**Comment by machaval** [comment]
Hi @jmasseoavio thanks for  letting us know this. Yes this was an issue and we just fix it please try latest version and let us know.

Also would love to hear feedback from you in what use case you are using this.

**Comment by jmasseoavio** [comment]
I'll leave feedback here.  I'm interested in evaluating 'dw' for use cases where I would use a tool like 'jq' or 'yq' or 'perl' currently to execute transformations and extractions on the command line.  Tools like jq are wonderful but it only supports JSON data and is not as powerful as DataWeave.  Using 'dw' would allow me one tool to work with multiple types of data and also to xform from one format to another.  Let me know if you require additional details or an example.  Thank you for resolving the issue.

**Comment by machaval** [comment]
Thanks @jmasseoavio I think this is good enough. One question what kind of package would you prefer us to distribute this tool for linux? Any thoughts.

Hope you are able to substitute jq yq perl or any other query and transformation tool. If you have any question ask in stack-overflow with the data-weave label and we will answer it.

Enjoy the tool,
