### ISSUE TITLE
Unable to resolve reference to payload error

### ISSUE THREAD

**Issue by ciwchris** [mulesoft-labs/data-weave-native#2]
**Describe the bug**
Running second example in README.md produces the error:

> [Error] Unable to resolve reference of payload.

**To Reproduce**
Steps to reproduce the behavior: Run second example in README.md

```
> cat users.json | dw "output application/json --- payload filter (item) -> item.age > 17"
```

**Expected behavior**

The same result as the first example.

**Desktop (please complete the following information):**

 - OS: Arch Linux

**Other info**

Thank you for creating this. I'm new to this space and was thankful when I came across it. I do have other questions about the application. First, when I run the first example it runs successfully but it also outputs the following messages:

> Unable to load descriptor `META-INF/dw-extensions.dwl` reasons: 
Unable to resolve module with identifier dw::Core.
Unknown location

Next, the third example uses double quotes within the script which causes an error. They need to be escaped or single quotes used.

Finally, it would be helpful to see an example using the `-main` argument. I'm not sure how it is to be used.

**Comment by machaval** [comment]
Thanks for reporting this. I will try to fix all your issues ASAP.  This project was built for a hackathon, but I will spent some time to improve its quality and docs so you can enjoy it. Will be back to you soon with updates.

**Comment by ciwchris** [comment]
I appreciate that. Thank you. It has already been helpful to me as I explore the DataWeave syntax.

**Comment by machaval** [comment]
I've just pushed two fixes one to fix the 
`> cat users.json | dw "output application/json --- payload filter (item) -> item.age > 17"`
And the other to fix the 

> 
> Unable to load descriptor META-INF/dw-extensions.dwl reasons:
> Unable to resolve module with identifier dw::Core.
> Unknown location

Please if you have any feedback is more than welcome . Thanks
