### ISSUE TITLE
Set in/out mimetypes as input parameters, env vars

### ISSUE THREAD

**Issue by jerneyio** [mulesoft-labs/data-weave-native#4]
When a client is dealing with a single API, the input/output mimetypes are typically constant, but the CLI does not accomodate for this. The DW CLI seems to default to the following when it doesn't have enough information to determine mimetype:

`$ dw input payload application/json output application/dw ...`

So if your input/output is anything other that json/dw, you need to explicitly set it every time.

It would be nice to pass in what you'd like:

`$ dw -input payload '/file' application/xml -output application/xml 'payload root`

It would be also nice if you could use defaults as env vars as well:

```
$ echo $DW_DEFAULT_INPUT_MIMETYPE
application/xml
$ echo $DW_DEFAULT_OUTPUT_MIMETYPE
application/xml
$ curl ... | dw 'payload.root'` # will take in and output xml
```

Input parameters should override env vars, and env vars should override `dw` defaults.

**Comment by machaval** [comment]
Done. Enjoy it
