### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by venkatkrishnappa** [mulesoft-labs/data-weave-native#8]
Is there a windows version of dataweave cli ? If not can it be added ?

**Comment by machaval** [comment]
We are planning to add one. We just need to see how to configure travis to build it.

**Comment by venkatkrishnappa** [comment]
Thanks for the confirmation. Will wait for it to be added :)

**Comment by machaval** [comment]
Currently I found that we are limited by our gradle plugin. So if you can vote this issue https://github.com/palantir/gradle-graal/issues/184 so it can get done

**Comment by venkatkrishnappa** [comment]
Have voted. Thanks

**Comment by vishalhalbe** [comment]
guys is this available now? where do I download it from?

**Comment by rubin55** [comment]
Lacking a windows binary, maybe some build instructions?

**Comment by machaval** [comment]
After several days of working it is finally here!!! Please try it out and let us know

**Comment by machaval** [comment]
Look at the Readme for the new link ;)
